#!/usr/bin/python
#
# Author: Hugo Haas <hugo@larve.net>
# License: GPLv2

import sys
import getopt
from Store import Store
from CommandlineInterface import CommandlineInterface
from TextInterface import TextInterface
from GtkInterface import GtkInterface,GtkUnavailable
from Version import Version

def usage(exitcode = 0):
    print "picfolio-metadata %s" % Version.v
    print "(c) 2003-2004 Hugo Haas <hugo@larve.net>"
    print """
Usage:
  picfolio-metadata [options] <image name> <image name> ...

Options:
-f, --file=		specify the file where meta-data is stored
			(default: picfolio/picfolio.xml)
-D, --directory		set the metadata for the directory
-t, --title=		specify the title for the object
-d, --description=	specify the description for the object
-h, --help		this message
"""
    sys.exit(exitcode)

def main():
    file = "picfolio/picfolio.xml"

    args = sys.argv[1:]
    # optlist broke -d / -D
    try:
        optlist, args = getopt.getopt(args, 'f:t:d:Dgh',
                                      ["title=",
                                       "description=",
                                       "directory",
                                       "gtk",
                                       "help"])
    except getopt.error, msg:
        print >>sys.stderr, "ERROR: %s\n" % msg
        usage(2)
    cli = 0
    directory = 0
    has_title = 0
    has_desc = 0
    use_gtk = 0
    title = None
    description = None
    for o in optlist:
        name = o[0]
        value = o[1]
        if name in ('-f', '--file'):
            file = value
        elif name in ('-t', '--title'):
            cli = 1
            has_title = 1
            title = value
        elif name in ('-d', '--description'):
            cli = 1
            has_desc = 1
            description = value
        elif name in ('-D', '--directory'):
            args = [ None ] + args
        elif name in ('-g', '--gtk'):
            use_gtk = 1
        elif name in ('-h', '--help'):
            usage()
    picfolio = Store(file)
    if cli:
        ui = CommandlineInterface(picfolio)
        for arg in args:
            ui.enter_metadata(arg, has_title, title, has_desc, description)
    elif use_gtk:
        try:
            ui = GtkInterface(picfolio, args)
            # Not reached
            sys.exit(0)
        except GtkUnavailable:
            print "GTK not available"
            sys.exit(1)
    else:
        ui = TextInterface(picfolio)
        for arg in args:
            ui.enter_metadata(arg)
    picfolio.save(ui.info)
    sys.exit(0)

if __name__ == "__main__":
    main()
