#!/bin/sh -e

VERSION_FILE=Version.py

if [ ! -f $VERSION_FILE ]; then
    echo "Please go into the picfolio-mde directory."
    exit
fi

ORIG=$PWD

VERSION=`egrep '^[[:space:]]*v' Version.py | cut -d\" -f 2`

echo -n "Preparing $VERSION release; proceed? "
read yn
echo
if [ "x$yn" != "xy" ]; then
    echo "Aborting"
    exit
fi

DIRNAME=picfolio-mde-$VERSION
DIR=/tmp/$DIRNAME
TARGET=/tmp/$DIRNAME.tar.bz2

if [ -d $DIR ]; then
    echo "Aborting: $DIR exists"
    exit
fi

if [ -f $TARGET ]; then
    echo "Aborting: $TARGET exists"
    exit
fi

cp -a . $DIR
cd /tmp
tar cvjf $TARGET $DIRNAME --exclude .cvsignore --exclude CVS --exclude prepare-release --exclude-from $ORIG/.cvsignore 

rm -rf $DIR

echo
echo -n "Upload to ftp.berlios.de? "
read yn
echo
if [ "x$yn" != "xy" ]; then
    echo "Not uploading"
    echo "Available at $TARGET"
else
    curl -v -T $TARGET ftp://ftp.berlios.de/incoming/
fi

